name: mvats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  desktop_drop: ^0.4.4
  path: ^1.8.3
  http: ^1.2.0
  video_player: ^2.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
